spring:
    datasource:
        url: jdbc:mysql://localhost:3306/employee_system_ver2
        username: springstudent
        password: springstudent
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true